import {InMemoryDbService} from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {

  createDb() {
    const heroes = [
      {
        id: 1,
        name: 'Tippa Raju',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:2,name:'Pedda Chennappa'},{id:3,name:'Chinna Chennappa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
     },
      {
        id: 2,
        name: 'Pedda Chennappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:4,name:'Linga Raju'},{id:7,name:'Dassappa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:1, name:'Tippa Raju'}]
      },
      {
        id: 3,
        name: 'Chinna Chennappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:26,name:'Kesavappa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:1, name:'Tippa Raju'}]
      },
      {
        id: 4,
        name: 'Linga Raju',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:5,name:'Papa Raju'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:2, name:'Pedda Chennappa'}]
      },
      {
        id: 5,
        name: 'Papa Raju',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:6,name:'Venkata Narasappa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:4, name:'Linga Raju'}]
      },
      {
        id: 6,
        name: 'Venkata Narasappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:27,name:' Venkata Kesavappa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:5, name:'Papa Raju'}]
      },
      {
        id: 7,
        name: 'Dassappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:8,name:' Venkata Ramanna'},{id:16,name:' Venkata Narayanappa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:2, name:'Pedda Chennappa'}]
      },
      {
        id: 8,
        name: 'Venkata Ramanna',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:9,name:'Venkata Rayappa'},{id:10,name:'Dasapa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:7,name:'Dassappa'}]
      },
      {
        id: 9,
        name: 'Venkata Rayappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id: 10,
        name: 'Dassappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:11, name:'Dasapa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id: 11,
        name: 'Dasappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:12, name:'Surya Narayana Rao (Adopted Son)'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:12,
        name: 'Surya Naraya Rao',
        dob:'',
        dod:'',
        gender:'male',
        sons:[
          {id:13, name:'Sambasiva Rao'},
          {id:14, name:'Sudhakar'},
          {id:15, name:'Ramachandra Rao'}
      ],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:13, name: 'Sambasiva Rao',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:28, name:'Eswar Praveen'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:14,
        name: 'Sudhakar',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:29, name:'Surya Prakash'},{id:30, name:'Sarat Chandra'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:15,
        name: 'Ramachandra Rao',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:31, name:'Praneeth'},{id:32, name:'Anoop'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:16,
        name: 'Venkata Narayanappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:17, name:'Venkata Narasappa'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:17,
        name: 'Venkata Narasappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:18, name:'Venkata Rayappa'},
              {id:33, name: 'Krishtrao'},
              {id:34, name: 'Surya Narayana Rao (Adoption to Dasappa)'},
              {id:35, name: 'Ramappa'},
              {id:36, name: 'Srinivasa Rao'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:18,
        name: 'Venkata Rayappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:19, name:'Venkata Subba Rao'},
              {id:25, name:'Venkata Narasappa'},
              {id:37, name: 'Ramadas'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:19,
        name: 'Venkata Subba Rao',
        dob:'',
        dod:'',
        gender:'male',
        sons:[ {id:20, name: 'Krishna Murthy'},
                {id:23, name: 'Ramachandra Rao'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:20,
        name: 'Krishna Murthy',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:21, name:'Sree Nath'},
              {id:22, name: 'Sureendra Nath'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:21,
        name: 'Sree Nath',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:22,
        name: 'Surendra Nath',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:38, name:'Sanketh'},
              {id:39, name:'Ruthvic'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:23,
        name: 'Ramachandra Rao',
        dob:'',
        dod:'',
        gender:'male',
        sons:[{id:24, name:'Sasidhar'}],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:24,
        name: 'Sasidhar',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:25,
        name: 'Venkata Narasappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[]
      },
      {
        id:26,
        name: 'Kesavappa ',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:3, name: 'Chinna Chennappa'}]
      },
      {
        id:27,
        name: 'Venkata Kesavappa ',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[{id:6, name:'Venkata Narasappa'}],
        description: 'Adoptation to Venkata Rayappa'
      },
      {
        id:28,
        name: 'Eswar Praveen',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:29,
        name: 'Surya Prakash',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:30,
        name: 'Sarat Chandra',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:31,
        name: 'Praneeth',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:32,
        name: ' Anoop',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:33,
        name: ' Krishtrao',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:34,
        name: 'Surya Narayana Rao',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: 'Adoption to Dasappa'
      },
      {
        id:35,
        name: ' Ramappa',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:36,
        name: ' Srinivasa Rao',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:37,
        name: ' Ramadas ',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:38,
        name: ' Sanketh ',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      },
      {
        id:39,
        name: ' Ruthvic ',
        dob:'',
        dod:'',
        gender:'male',
        sons:[],
        wiwes:[],
        daughters:[],
        mother:[],
        father:[],
        description: ''
      }
    ];
    return {heroes};
  }

}
